version: '3'

volumes:
  db: {}
services:
  db:
    container_name: 'avito_postgres'
    command: postgres -c listen_addresses='*'
    build:
      ./src/db/
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=testbase
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      - service_mail=''
      - password=
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - db