[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "1.5.0"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.6.0"

[[constraint]]
  name = "github.com/google/gofuzz"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.8.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.8.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/yaml.v3"
